### ISSUE TITLE
How to remove the component???

### ISSUE THREAD

**Issue by danielbrunt57** [c-st/auto_areas#25]
I now have a slew of left over read-only entities after removing the yaml config and HACS component...

![image](https://user-images.githubusercontent.com/49846893/236583829-dfda9b71-4711-4fbc-aa5f-0c92236ddc64.png)

**Comment by danielbrunt57** [comment]
```
service: recorder.purge_entities
data:
  domains: []
  entity_globs: binary_sensor.area_presence_*
  keep_days: 0
```
```
service: recorder.purge_entities
data:
  domains: []
  entity_globs: switch.sensor.area_presence_*
  keep_days: 0
```
